apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-read-data-storage
  namespace: python-ide
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-read-data-storage-secrets
  namespace: data-storage
rules:
- apiGroups: [""]
  resources:
  - secrets
  - secrets/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectrulesreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-read-data-storage-secrets-rb
  namespace: data-storage
subjects:
- kind: ServiceAccount
  name: sa-read-data-storage
  namespace: python-ide
roleRef:
  kind: Role
  name: eso-read-data-storage-secrets
  apiGroup: rbac.authorization.k8s.io
