apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
spec:
  project: default

  sources:
  - repoURL: https://argoproj.github.io/argo-helm
    chart: argo-events
    targetRevision: 2.4.11
    helm:
      valueFiles:
        - $values/helm-values/argo-events-values.yaml
      timeout: 200
  - repoURL: https://github.com/mdotloading/wdski23a-mlops-gitops.git
    targetRevision: main
    ref: values
  - repoURL: https://github.com/mdotloading/wdski23a-mlops-gitops.git
    targetRevision: main
    path: argo-events
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-events

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
