apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default

  sources:
  - repoURL: https://argoproj.github.io/argo-helm
    chart: argo-workflows
    targetRevision: 0.46.4
    helm:
      valueFiles:
        - $values/helm-values/argo-workflows-values.yaml
      timeout: 200
  - repoURL: https://github.com/mdotloading/wdski23a-mlops-gitops.git
    targetRevision: main
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
