apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mdotloading/wdski23a-mlops-gitops.git
    targetRevision: main
    path: namespaces

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
