apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-events-workflow-submit
  namespace: argo-workflows
rules:
- apiGroups: ["argoproj.io"]
  resources:
  - workflows
  - workflowtemplates
  verbs:
  - get
  - list
  - watch
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-events-workflow-submit
  namespace: argo-workflows
subjects:
- kind: ServiceAccount
  name: argo-events-sensor
  namespace: argo-events
roleRef:
  kind: Role
  name: argo-events-workflow-submit
  apiGroup: rbac.authorization.k8s.io
